version: '3.9'

services:
    postgres:
        image: postgres
        container_name: go-exchange-postgres
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 1
            POSTGRES_DB: CryptoAuth
        ports:
            - "5432:5432"
        networks:
            - go-exchange-network
        volumes:
            - postgres_data:/var/lib/postgresql/data

    prometheus:
        image: prom/prometheus
        container_name: go-exchange-prometheus
        volumes:
            - ./prometheus.yml:/etc/prometheus/prometheus.yml
        ports:
            - "9090:9090"
        networks:
            - go-exchange-network

    grafana:
        image: grafana/grafana
        container_name: go-exchange-grafana
        ports:
            - "3030:3030"
        networks:
            - go-exchange-network
        volumes:
            - grafana_data:/var/lib/grafana

    zookeeper:
        image: confluentinc/cp-zookeeper:7.4.0
        hostname: zookeeper
        container_name: go-exchange-zookeeper
        ports:
            - "2181:2181"
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
            ZOOKEEPERS_SERVERS: zookeeper:2888
        networks:
            - go-exchange-network

    kafka:
        image: confluentinc/cp-kafka:7.4.0
        container_name: go-exchange-kafka
        ports:
            - "9092:9092"
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092, PLAINTEXT_HOST://localhost:9092
            KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092, PLAINTEXT_HOST://0.0.0.0:9092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT, PLAINTEXT_HOST:PLAINTEXT
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_CONTROLLER_QUORUM_VOTERS: ""
            KAFKA_KRAFT_BROKER_ENABLED: "false"
            KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
        volumes:
            - kafka_data:/var/lib/kafka/data
        depends_on:
            - zookeeper
        networks:
            - go-exchange-network

    auth:
        image: go-exchange-auth
        container_name: go-exchange-auth
        build: 
            context: ../go-exchange-auth
        ports:
            - "5711:5711"
            - "2111:2111"
        env_file:
            - ../go-exchange-auth/.env
        depends_on:
            - postgres
        networks:
            - go-exchange-network
        volumes:
            - ../go-exchange-auth/.env:/app/.env
            - ../go-exchange-auth/config:/app/config
            - ../go-exchange-auth/migrations:/app/migrations

    trades:
        image: go-exchange-trades
        container_name: go-exchange-trades
        build: 
            context: ../go-exchange-trades
        ports:
            - "5721:5711"
            - "2121:2111"
        env_file:
            - ../go-exchange-trades/.env
        networks:
            - go-exchange-network
        volumes:
            - ../go-exchange-trades/.env:/app/.env
            - ../go-exchange-trades/config:/app/config


networks:
    go-exchange-network:
        driver: bridge

volumes:
    postgres_data:
    grafana_data:
    kafka_data: